//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ControladorServicos.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceRotaSoap", Namespace="http://jointecnologia.com/")]
    public partial class WebServiceRota : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback IncluiColetaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaFasesColetaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaCaminhoDocumentosOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadArquivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelaColetaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServiceRota() {
            this.Url = global::ControladorServicos.Properties.Settings.Default.ControladorServicos_WebReference_WebServiceRota;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event IncluiColetaCompletedEventHandler IncluiColetaCompleted;
        
        /// <remarks/>
        public event ConsultaFasesColetaCompletedEventHandler ConsultaFasesColetaCompleted;
        
        /// <remarks/>
        public event ConsultaCaminhoDocumentosCompletedEventHandler ConsultaCaminhoDocumentosCompleted;
        
        /// <remarks/>
        public event UploadArquivoCompletedEventHandler UploadArquivoCompleted;
        
        /// <remarks/>
        public event CancelaColetaCompletedEventHandler CancelaColetaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jointecnologia.com/IncluiColeta", RequestNamespace="http://jointecnologia.com/", ResponseNamespace="http://jointecnologia.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string IncluiColeta(
                    string sLogin, 
                    string sSenha, 
                    string cliCPF, 
                    string cliRG, 
                    string cliNome, 
                    System.DateTime cliDataNascimento, 
                    char cliSexo, 
                    string cliTelefone1, 
                    string cliTelefone2, 
                    string cliTelefone3, 
                    string cliEndereco, 
                    string cliComplemento, 
                    string cliBairro, 
                    string cliCidade, 
                    string cliUF, 
                    string cliCEP, 
                    string cliPontoReferencia, 
                    System.DateTime colDataAgendamento, 
                    char colTurnoAgendamento, 
                    int colQuantFolhas, 
                    int colCodTipoDocumento, 
                    string colNumeroAdesao, 
                    string colObservacoes) {
            object[] results = this.Invoke("IncluiColeta", new object[] {
                        sLogin,
                        sSenha,
                        cliCPF,
                        cliRG,
                        cliNome,
                        cliDataNascimento,
                        cliSexo,
                        cliTelefone1,
                        cliTelefone2,
                        cliTelefone3,
                        cliEndereco,
                        cliComplemento,
                        cliBairro,
                        cliCidade,
                        cliUF,
                        cliCEP,
                        cliPontoReferencia,
                        colDataAgendamento,
                        colTurnoAgendamento,
                        colQuantFolhas,
                        colCodTipoDocumento,
                        colNumeroAdesao,
                        colObservacoes});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void IncluiColetaAsync(
                    string sLogin, 
                    string sSenha, 
                    string cliCPF, 
                    string cliRG, 
                    string cliNome, 
                    System.DateTime cliDataNascimento, 
                    char cliSexo, 
                    string cliTelefone1, 
                    string cliTelefone2, 
                    string cliTelefone3, 
                    string cliEndereco, 
                    string cliComplemento, 
                    string cliBairro, 
                    string cliCidade, 
                    string cliUF, 
                    string cliCEP, 
                    string cliPontoReferencia, 
                    System.DateTime colDataAgendamento, 
                    char colTurnoAgendamento, 
                    int colQuantFolhas, 
                    int colCodTipoDocumento, 
                    string colNumeroAdesao, 
                    string colObservacoes) {
            this.IncluiColetaAsync(sLogin, sSenha, cliCPF, cliRG, cliNome, cliDataNascimento, cliSexo, cliTelefone1, cliTelefone2, cliTelefone3, cliEndereco, cliComplemento, cliBairro, cliCidade, cliUF, cliCEP, cliPontoReferencia, colDataAgendamento, colTurnoAgendamento, colQuantFolhas, colCodTipoDocumento, colNumeroAdesao, colObservacoes, null);
        }
        
        /// <remarks/>
        public void IncluiColetaAsync(
                    string sLogin, 
                    string sSenha, 
                    string cliCPF, 
                    string cliRG, 
                    string cliNome, 
                    System.DateTime cliDataNascimento, 
                    char cliSexo, 
                    string cliTelefone1, 
                    string cliTelefone2, 
                    string cliTelefone3, 
                    string cliEndereco, 
                    string cliComplemento, 
                    string cliBairro, 
                    string cliCidade, 
                    string cliUF, 
                    string cliCEP, 
                    string cliPontoReferencia, 
                    System.DateTime colDataAgendamento, 
                    char colTurnoAgendamento, 
                    int colQuantFolhas, 
                    int colCodTipoDocumento, 
                    string colNumeroAdesao, 
                    string colObservacoes, 
                    object userState) {
            if ((this.IncluiColetaOperationCompleted == null)) {
                this.IncluiColetaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIncluiColetaOperationCompleted);
            }
            this.InvokeAsync("IncluiColeta", new object[] {
                        sLogin,
                        sSenha,
                        cliCPF,
                        cliRG,
                        cliNome,
                        cliDataNascimento,
                        cliSexo,
                        cliTelefone1,
                        cliTelefone2,
                        cliTelefone3,
                        cliEndereco,
                        cliComplemento,
                        cliBairro,
                        cliCidade,
                        cliUF,
                        cliCEP,
                        cliPontoReferencia,
                        colDataAgendamento,
                        colTurnoAgendamento,
                        colQuantFolhas,
                        colCodTipoDocumento,
                        colNumeroAdesao,
                        colObservacoes}, this.IncluiColetaOperationCompleted, userState);
        }
        
        private void OnIncluiColetaOperationCompleted(object arg) {
            if ((this.IncluiColetaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IncluiColetaCompleted(this, new IncluiColetaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jointecnologia.com/ConsultaFasesColeta", RequestNamespace="http://jointecnologia.com/", ResponseNamespace="http://jointecnologia.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ConsultaFasesColeta(string sLogin, string sSenha, int CodigoColeta) {
            object[] results = this.Invoke("ConsultaFasesColeta", new object[] {
                        sLogin,
                        sSenha,
                        CodigoColeta});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaFasesColetaAsync(string sLogin, string sSenha, int CodigoColeta) {
            this.ConsultaFasesColetaAsync(sLogin, sSenha, CodigoColeta, null);
        }
        
        /// <remarks/>
        public void ConsultaFasesColetaAsync(string sLogin, string sSenha, int CodigoColeta, object userState) {
            if ((this.ConsultaFasesColetaOperationCompleted == null)) {
                this.ConsultaFasesColetaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaFasesColetaOperationCompleted);
            }
            this.InvokeAsync("ConsultaFasesColeta", new object[] {
                        sLogin,
                        sSenha,
                        CodigoColeta}, this.ConsultaFasesColetaOperationCompleted, userState);
        }
        
        private void OnConsultaFasesColetaOperationCompleted(object arg) {
            if ((this.ConsultaFasesColetaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaFasesColetaCompleted(this, new ConsultaFasesColetaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jointecnologia.com/ConsultaCaminhoDocumentos", RequestNamespace="http://jointecnologia.com/", ResponseNamespace="http://jointecnologia.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ConsultaCaminhoDocumentos(string sLogin, string sSenha, int CodigoColeta) {
            object[] results = this.Invoke("ConsultaCaminhoDocumentos", new object[] {
                        sLogin,
                        sSenha,
                        CodigoColeta});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaCaminhoDocumentosAsync(string sLogin, string sSenha, int CodigoColeta) {
            this.ConsultaCaminhoDocumentosAsync(sLogin, sSenha, CodigoColeta, null);
        }
        
        /// <remarks/>
        public void ConsultaCaminhoDocumentosAsync(string sLogin, string sSenha, int CodigoColeta, object userState) {
            if ((this.ConsultaCaminhoDocumentosOperationCompleted == null)) {
                this.ConsultaCaminhoDocumentosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaCaminhoDocumentosOperationCompleted);
            }
            this.InvokeAsync("ConsultaCaminhoDocumentos", new object[] {
                        sLogin,
                        sSenha,
                        CodigoColeta}, this.ConsultaCaminhoDocumentosOperationCompleted, userState);
        }
        
        private void OnConsultaCaminhoDocumentosOperationCompleted(object arg) {
            if ((this.ConsultaCaminhoDocumentosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaCaminhoDocumentosCompleted(this, new ConsultaCaminhoDocumentosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jointecnologia.com/UploadArquivo", RequestNamespace="http://jointecnologia.com/", ResponseNamespace="http://jointecnologia.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UploadArquivo(string sLogin, string sSenha, int CodigoColeta, string sDescricaoArquivo, string sNomeOriginalArquivo, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] Arquivo) {
            object[] results = this.Invoke("UploadArquivo", new object[] {
                        sLogin,
                        sSenha,
                        CodigoColeta,
                        sDescricaoArquivo,
                        sNomeOriginalArquivo,
                        Arquivo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UploadArquivoAsync(string sLogin, string sSenha, int CodigoColeta, string sDescricaoArquivo, string sNomeOriginalArquivo, byte[] Arquivo) {
            this.UploadArquivoAsync(sLogin, sSenha, CodigoColeta, sDescricaoArquivo, sNomeOriginalArquivo, Arquivo, null);
        }
        
        /// <remarks/>
        public void UploadArquivoAsync(string sLogin, string sSenha, int CodigoColeta, string sDescricaoArquivo, string sNomeOriginalArquivo, byte[] Arquivo, object userState) {
            if ((this.UploadArquivoOperationCompleted == null)) {
                this.UploadArquivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadArquivoOperationCompleted);
            }
            this.InvokeAsync("UploadArquivo", new object[] {
                        sLogin,
                        sSenha,
                        CodigoColeta,
                        sDescricaoArquivo,
                        sNomeOriginalArquivo,
                        Arquivo}, this.UploadArquivoOperationCompleted, userState);
        }
        
        private void OnUploadArquivoOperationCompleted(object arg) {
            if ((this.UploadArquivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadArquivoCompleted(this, new UploadArquivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jointecnologia.com/CancelaColeta", RequestNamespace="http://jointecnologia.com/", ResponseNamespace="http://jointecnologia.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CancelaColeta(string sLogin, string sSenha, int CodigoColeta) {
            object[] results = this.Invoke("CancelaColeta", new object[] {
                        sLogin,
                        sSenha,
                        CodigoColeta});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CancelaColetaAsync(string sLogin, string sSenha, int CodigoColeta) {
            this.CancelaColetaAsync(sLogin, sSenha, CodigoColeta, null);
        }
        
        /// <remarks/>
        public void CancelaColetaAsync(string sLogin, string sSenha, int CodigoColeta, object userState) {
            if ((this.CancelaColetaOperationCompleted == null)) {
                this.CancelaColetaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelaColetaOperationCompleted);
            }
            this.InvokeAsync("CancelaColeta", new object[] {
                        sLogin,
                        sSenha,
                        CodigoColeta}, this.CancelaColetaOperationCompleted, userState);
        }
        
        private void OnCancelaColetaOperationCompleted(object arg) {
            if ((this.CancelaColetaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelaColetaCompleted(this, new CancelaColetaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void IncluiColetaCompletedEventHandler(object sender, IncluiColetaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IncluiColetaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IncluiColetaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ConsultaFasesColetaCompletedEventHandler(object sender, ConsultaFasesColetaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaFasesColetaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaFasesColetaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ConsultaCaminhoDocumentosCompletedEventHandler(object sender, ConsultaCaminhoDocumentosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaCaminhoDocumentosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaCaminhoDocumentosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void UploadArquivoCompletedEventHandler(object sender, UploadArquivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadArquivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadArquivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void CancelaColetaCompletedEventHandler(object sender, CancelaColetaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelaColetaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelaColetaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591